name: Build FutsFarm Apps

# Cho phép bạn vào tab Actions trên GitHub và tự bấm nút "Run workflow"
on:
  workflow_dispatch: 

env:
  # Lệnh lách cảnh báo Node.js 20 của GitHub
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Lấy mã nguồn
        uses: actions/checkout@v4
      
      - name: Cài đặt Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Cài đặt Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Tải thư viện
        run: flutter pub get
        
      - name: Build file APK
        run: flutter build apk --release
        
      - name: Xuất file APK lên GitHub
        uses: actions/upload-artifact@v4
        with:
          name: FutsFarm-Android-APK
          path: build/app/outputs/flutter-apk/app-release.apk

  build-ios-unsigned:
    name: Build iOS (Không cần chữ ký)
    runs-on: macos-latest
    steps:
      - name: Lấy mã nguồn
        uses: actions/checkout@v4
        
      - name: Cài đặt Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Tải thư viện
        run: flutter pub get
        
      - name: Build iOS (Lách lỗi Code Signing)
        run: flutter build ios --release --no-codesign
        
      - name: Đóng gói thành file IPA cơ bản
        run: |
          mkdir -p Payload
          mv build/ios/iphoneos/Runner.app Payload/
          zip -r FutsFarm-iOS-Unsigned.ipa Payload
          
      - name: Xuất file IPA lên GitHub
        uses: actions/upload-artifact@v4
        with:
          name: FutsFarm-iOS-Unsigned
          path: FutsFarm-iOS-Unsigned.ipa
